import "@rainbow-me/rainbowkit/styles.css";

import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <div className="w-full flex justify-center min-h-screen bg-[#F6F6F6]">
            <div className=" w-full lg:max-w-5xl lg:px-0 px-5">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
